apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sybline-broker.fullname" . }}-salt-secret
type: Opaque
data:
  # Base64-encoded key-value pairs
  salt: {{ randAlphaNum (int .Values.secrets.salt.autoGenerate.length) | b64enc }}