{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sybline-broker.serviceAccountName" . }}
  labels:
    {{- include "sybline-broker.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sybline-broker.fullname" . }}-role
  labels:
    {{- include "sybline-broker.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["list", "get"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  {{ include "sybline-broker.fullname" . }}-rolebinding
  labels:
    {{- include "sybline-broker.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sybline-broker.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "sybline-broker.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
