{{- $serverPort  := .Values.statefulset.env.SERVER_PORT -}}
{{- $restPort  := .Values.statefulset.env.REST_PORT -}}
{{- range $i, $val := until (int .Values.replicaCount) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s-%s" ( $.Release.Name ) "sybline-service" (toString $i) }}
  labels:
    app: sybline
spec:
  ports:
  - protocol: TCP
    port: {{ $serverPort }}
    name: web-grpc
  - protocol: TCP
    port: {{ $restPort }}
    name: web-rest
  selector:
    statefulset.kubernetes.io/pod-name: {{ printf "%s-%s-%s" ( $.Release.Name ) $.Values.statefulset.name (toString $i) }}
---
{{- end }}