# Default values for sybline-broker

replicaCount: 3

image:
  name: greedykomodo/sybline:test
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

statefulset:
  name: sybline-statefulset
  env:
    SERVER_PORT: 2221
    TLS_ENABLED: false
    TLS_VERIFY_SKIP: false
    SNAPSHOT_THRESHOLD: 100000
    TOKEN_DURATION: 10800 # 6 hours is the default for the helm chart
    REST_PORT: 7878
  pod:
    # Resources per pod
    resources:
      # defaults have not be tested for ideal production settings
      limits:
        cpu: 1000m
        memory: 2000Mi
      requests:
        cpu: 500m

ingress:
  # By Default the Ingress is disabled
  enable: false
  class: nginx

secrets:
  salt:
    autoGenerate: 
      enable: true # currently ignored
      length: 30
  #   overwrite: false
  #   existing:
  #     enable: false
  #     name: ""
  # mtls is ignored if statefulset.env.TLS_ENABLED is false
  mtls:  
    keyURI: "certificates/key.pem"
    caCertURI: "certificates/ca-cert.pem"
    certURI: "certificates/cert.pem"


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""